version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: deployment-scripts/npm-install.sh
      runas: root
      timeout: 300    
  ApplicationStart:
    - location: deployment-scripts/npm-start.sh
      runas: root
      timeout: 60
